
services:
  - type: web
    name: task-manager
    env: node
    plan: free
    buildCommand: cd client && npm ci && npm run build && cd ../server && npm ci
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/database.sqlite
      - key: ALLOWED_ORIGINS
        value: https://task-manager.onrender.com,https://*.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOG_LEVEL
        value: info
